# Generated by Django 3.1.7 on 2021-03-10 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('tempo_preparo', models.IntegerField()),
                ('rendimento', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('data_postagem', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
